export const thankMsg= [
    "I grew up with the internet. I knew arin from his animator days as egoraptor. I started watching when he started game grumps with jon, but stopped watching when jon left the show. I was one of those guys who were pretty pissed about jon leaving. But then i started watching them again on and off for a while until that wind waker episode. I love both dan and arin. They shaped me as a person. And im glad they did.",
    "I was in fifth grade when I first found out about the grumps. I was really really sick in bed and I had been for a few weeks. So I naturally wanted to look up let's play's of one of my favorite games at the time. Super Mario 3d World. and i found the grumps. \n  They made me laugh the hardest I had in a long time. I am eternally thankful for that.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dictum massa nec enim lobortis porta. Fusce euismod pretium posuere. Aenean pharetra ornare libero, quis rhoncus magna varius sed. Mauris venenatis vehicula ligula, ac posuere ligula maximus vitae. Aliquam sed turpis facilisis, feugiat felis id, hendrerit quam. Duis auctor urna eu tortor ultricies pellentesque. Etiam sollicitudin volutpat orci vel auctor. Praesent viverra ullamcorper neque sed viverra. Donec posuere augue sed lectus consectetur, et cursus elit accumsan. Donec in odio sed purus elementum vulputate. Proin at turpis odio. Suspendisse eleifend augue a tellus pellentesque, eget ornare enim pretium. Vivamus vitae lectus quam. Mauris sagittis interdum accumsan. Sed mattis risus tortor, nec pretium est venenatis vitae.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dictum massa nec enim lobortis porta. Fusce euismod pretium posuere. Aenean pharetra ornare libero, quis rhoncus magna varius sed. Mauris venenatis vehicula ligula, ac posuere ligula maximus vitae. Aliquam sed turpis facilisis, feugiat felis id, hendrerit quam. Duis auctor urna eu tortor ultricies pellentesque. Etiam sollicitudin volutpat orci vel auctor. Praesent viverra ullamcorper neque sed viverra. Donec posuere augue sed lectus consectetur, et cursus elit accumsan. Donec in odio sed purus elementum vulputate. Proin at turpis odio. Suspendisse eleifend augue a tellus pellentesque, eget ornare enim pretium. Vivamus vitae lectus quam. Mauris sagittis interdum accumsan. Sed mattis risus tortor, nec pretium est venenatis vitae.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dictum massa nec enim lobortis porta. Fusce euismod pretium posuere. Aenean pharetra ornare libero, quis rhoncus magna varius sed. Mauris venenatis vehicula ligula, ac posuere ligula maximus vitae. Aliquam sed turpis facilisis, feugiat felis id, hendrerit quam. Duis auctor urna eu tortor ultricies pellentesque. Etiam sollicitudin volutpat orci vel auctor. Praesent viverra ullamcorper neque sed viverra. Donec posuere augue sed lectus consectetur, et cursus elit accumsan. Donec in odio sed purus elementum vulputate. Proin at turpis odio. Suspendisse eleifend augue a tellus pellentesque, eget ornare enim pretium. Vivamus vitae lectus quam. Mauris sagittis interdum accumsan. Sed mattis risus tortor, nec pretium est venenatis vitae."
]
export const names = [
    "Sbeajy",
    "zOOVYzOOV",
]
export const profilePics= [
"https://cdn.discordapp.com/avatars/195544804988420096/2be24761d2ba1bf21159555bf3bdff35.png?size=128",
"https://cdn.discordapp.com/avatars/728372945759633469/4783286e15e8e0826a75e4fe5f7880fc.png?size=128",
"https://cdn.discordapp.com/avatars/728372945759633469/4783286e15e8e0826a75e4fe5f7880fc.png?size=128",
"https://cdn.discordapp.com/avatars/728372945759633469/4783286e15e8e0826a75e4fe5f7880fc.png?size=128"
]